### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by jastidinesh** [jastidinesh/SEBC#2]

**Comment by jastidinesh** [comment]
Started the Ec2 Instances.

**Comment by jastidinesh** [comment]
Completed the system configuration checks.

**Comment by jastidinesh** [comment]
Completed mysql replication.
When I first tried to install I forgot to disable 5.6 repo and that installed 5.6 even though the 5.5 is enabled probably because that is the latest. So, had to try a bunch of thing to get it work and when it actually worked mysqld service wont start. Something went wrong with the machine and it wasn't able to start the service. Tried debugging the logs couldn't find anything. So ended up getting a fresh new set of machines and restart the whole process again.

**Comment by jastidinesh** [comment]
Completed the installation of the CM.Did a fresh install probably 5-6 times. With one of the Ec2 AMIs' in CentOS 6.7 the root partition is not taking up all the space allocated for it, it is taking the default space of only 8GB and leaving the remaining as unallocated space. As the root partition size was only 8GB it was not sufficient for the CM installation and the CM setup process kept on failing. Tried multiple times to repartition the root volume to expand to the remaining size which ended up failing and also making the machine not bootable. 
Finally moved to a different AMI which used CentOS 7. During the installation in CentOS 7 there was an issue with openjdk1.8 already installed, which caused CM not be able to distribute the packages to the hosts. Which kept on throwing this error on the agents : `Caught unexpected exception in main loop. ValueError: too many values to unpack`. Fixed this my removing the openjdk from all the nodes. This might not be a viable solution as sometimes there might be other packages which are dependent on it and using that package.

**Comment by jastidinesh** [comment]
Completed the optional local repo installation step.

**Comment by mfernest** [comment]
Good work! 👍
